services:
  barcode-middleware:
    build: .
    image: barcode-mealie-middleware:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./middleware-data:/data
    env_file:
      - .env
